### ISSUE TITLE
Remove file description if not supplied

### ISSUE THREAD

**Issue by dwelle** [tomayac/browser-nativefs#2]
Readme says that `description` defaults to empty string, but the [code](https://github.com/tomayac/browser-nativefs/blob/836724b870717df0bf92e57250bd5c2108539d15/src/file-save-nativefs.mjs#L33-L35) defaults to parsing the `blob.type`. This results in custom description, instead of using the system/browser default.

I'm not sure what's the authoritative way to get the default, by from my testing not passing `description` at all, or passing `description: ""` both works.

Since the spec doesn't mark it as optional, I'd go with empty string. This will also align it with the readme.

Currently:

![image](https://user-images.githubusercontent.com/5153846/73134961-279ced80-403d-11ea-92da-f717c9056b5a.png)

Browser/system default:

![image](https://user-images.githubusercontent.com/5153846/73134962-2c61a180-403d-11ea-8f32-2d7a7377b553.png)

**Comment by tomayac** [comment]
This is a good catch, I have now removed this and released a new version v0.2.0. Will update Excalidraw in a minute…

**Comment by dwelle** [comment]
Thanks! :+1:
